trigger:
  branches:
    include:
    - master
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: default
    steps:
    - task: 6d15af64-176c-496d-b583-fd2ae21d4df4@1
      inputs:
        repository: self
        submodules: true
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - task: CmdLine@2
      displayName: 'npm install and build'
      inputs:
        script: |
          npm install -g @angular/cli
          npm install
          ng build --prod

