# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: default

variables:
  projectfile: '**/*Android.csproj'

steps:
- checkout: self
  submodules: true

- task: MSBuild@1
  displayName: 'Restore Packages'
  inputs:
    solution: '**/*.sln'
    msbuildArguments: '/t:Restore'

- task: XamarinAndroid@1
  displayName: 'Build android app'
  inputs:
    projectFile: $(projectfile)
    msbuildArguments: '/p:AndroidSdkDirectory=/android/sdk/'
